# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfd4c86599a1bcd545021bd3f2996c02a5caad790ab396c836aa83df8f52538fd97238921d0cfbd1dfe64569048a0e7fb0871587079d2ba0aae8409382d39721

test:
  secret_key_base: 6c4a9ffde7d30ae509b88f4a61e602aaaf12d49fc51e4aec45bf5a33c60c5a99b741cc38e40d5af8aaddcc763911f5a2704bd166dbc4cbe86b7b828b1f7de107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
